# workstation.yml
#
# Ansible playbook for workstation configuration
#
#

- name: Workstation Setup
  hosts: localhost
  user: root
  tasks:
    - name: install python and deps for ansible modules
      raw: dnf install -y python2 python2-dnf libselinux-python libsemanage-python python2-firewall

    - include: ansible/tasks/main.yml
    - include: ansible/tasks/chrome-fedora25.yml
    - include: ansible/tasks/automationTools.yml
    - include: ansible/tasks/psycopg2.yml
    - include: ansible/tasks/repo.yml

#
#- name: User Specific
#  hosts: localhost
#  become: true
#  become_user: gohan
#  tasks:
#     - name: get dropbox
#       raw:  cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzvf -
#
