# workstation.yml
#
# Ansible playbook for workstation configuration
#
#

- name: Workstation Setup
  hosts: localhost
  user: root
  tasks:
    - import_tasks: ansible/tasks/main.yml
    - import_tasks: ansible/tasks/chrome-fedora.yml
    - import_tasks: ansible/tasks/automationTools.yml
    - import_tasks: ansible/tasks/psycopg2.yml
    - import_tasks: ansible/tasks/repo.yml
    - import_tasks: ansible/tasks/dropbox.yml
    - import_tasks: ansible/tasks/visual-code.yml
    - import_tasks: ansible/tasks/docker.yml
