 - name: install packages
   dnf: name={{item}} state=installed
   with_items:
    - nano
    - vim
    - ipython
    - git
    - htop
    - keepass

 - name: virtualisation and automation
   dnf: name={{item}} state=installed
   with_items:
    - docker
    - vagrant
    - VirtualBox
    - akmod-VirtualBox

 # Docker
 - name: enable docker
   service:
    name: docker
    state: started
    enabled: yes

