 - name: install packages required for python psycogp2 package
   dnf: name={{item}} state=installed
   with_items:
    - python3-devel
    - redhat-rpm-config
    - gcc
    - python3-postgresql
    - postgresql-devel
