 - name: get current Release
   command: uname -r
   register: currentRelease

 - name: sysadmin tools
   dnf: name={{item}} state=installed
   with_items:
    - htop
    - ntop
    - nmap

 - name: virtualisation and automation
   dnf: name={{item}} state=installed
   with_items:
    - awscli
    - docker
    - vagrant
    - kernel-devel-{{ currentRelease['stdout'] }}
    - VirtualBox
    - akmod-VirtualBox

 - name: register virtualisation modules
   command: akmods --kernels 4.8.6-300.fc25.x86_64 
 
 - name: relaunch module service
   service:  
      name: systemd-modules-load.service
      state: restarted


 # Docker
 - group:
    name: docker
    state: present

 - name: enable docker
   service:
    name: docker
    state: started
    enabled: yes

# - name: pull docker images
#   docker_image:
#    name: {{item}}
#    with_items:
#     - nginx
#     - jenkins 
#   
