 - name: get current Release
   command: uname -r
   register: currentRelease

 - name: virtualisation and automation
   dnf: name={{item}} state=installed
   with_items:
    - awscli
    - vagrant
    - kernel-devel-{{ currentRelease['stdout'] }}
    - VirtualBox
    - akmod-VirtualBox

 - name: register virtualisation modules
   command: akmods --kernels {{ currentRelease['stdout'] }}
 
 - name: relaunch module service
   service:  
      name: systemd-modules-load.service
      state: restarted

