 - name: install Google Chrome repo
   copy: src=additional-repo.repo dest=/etc/yum.repos.d/

 - name: import Google Chrome signing key
   rpm_key: key=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

 - name: install packages
   dnf: name={{item}} state=installed
   with_items:
    - google-chrome-stable

