 - name: install docker repo
   copy: src=additional-repo.repo dest=/etc/yum.repos.d/

 - name: remove the fedora docker packages 
   dnf: name={{item}} state=absent autoremove=yes
   with_items:
     - docker-common 
     - docker-selinux 
     - docker-engine-selinux
     - docker-engine
     - docker 

 - name : docker repo 
   dnf: 
     name: dnf-plugins-core
     state: present

 - name: install docker repository
   command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
 
 - name: install docker
   dnf: name="{{ item }}" state=present
   with_items:
    - docker-ce

# - name: pull docker images
#  docker_image:
#   name: {{item}}
#   with_items:
#    - nginx
#    - jenkins
