 - name: install docker repo
   copy: src=additional-repo.repo dest=/etc/yum.repos.d/

 - name: remove the fedora docker packages
   dnf:
     name: ['docker-common', 'docker-selinux', 'docker-engine-selinux', 'docker-engine', 'docker']
     state: absent
     autoremove: yes

 - name: docker repo
   dnf:
     name: dnf-plugins-core
     state: installed

 - name: install docker
   dnf:
     name: ['docker-ce']
     state: installed

# - name: pull docker images
#  docker_image:
#   name: {{item}}
#   with_items:
#    - nginx
#    - jenkins
