 - name: install edition packages
   dnf: name={{item}} state=installed
   with_items:
    - wget
    - nano
    - ipython
    - git

 - name: install edition packages
   dnf: name={{item}} state=installed
   with_items:
    - keepass
    - dropbox
    - calibre 
    - inkscape
