 - name: get Fedora current Release
   command: rpm -E %fedora
   register: fedoraRelease
 
 - name: install the rpmfusion repo packages
   dnf: name={{ item }}
    state=present
   with_items:
     - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedoraRelease['stdout'] }}.noarch.rpm
     - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedoraRelease['stdout'] }}.noarch.rpm

 - name: install dev lib(required for YouCompleteMe)
   dnf: name={{item}} state=installed
    - automake
    - gcc
    - gcc-c++
    - kernel-devel
    - cmake

 - name: install framework dev packages
   dnf: name={{item}} state=installed
   with_items:
    - go
    - jq
    - jre
    - javaws
    - python2-virtualenv

 - name: install edition packages
   dnf: name={{item}} state=installed
   with_items:
    - banner
    - wget
    - nano
    - ipython
    - git
    - tig
    - gitk
    - tmux
    - vim-enhanced

 - name: install desktop packages
   dnf: name={{item}} state=installed
   with_items:
    - keepass
    - calibre
    - inkscape
    - vlc

 - name: install admin packages
   dnf: name={{item}} state=installed
   with_items:
    - htop
    - ntop
    - nmap
    - setools-console


