 - name: manage local repository arborescence
   group:
    name: gituser
    state: present

 - file:
    path: /REPOS/public
    state: directory
    mode: 0775
    owner: root
    group: gituser
 
 - file:
    path: /REPOS/private
    state: directory
    mode: 0775
    owner: root
    group: gituser
