# workstation.yml
#
# Ansible playbook for workstation configuration
#
#

- name: Workstation Setup
  hosts: localhost
  user: root
  tasks:
    - name: install python and deps for ansible modules
      raw: dnf install -y python2 python2-dnf libselinux-python libsemanage-python python2-firewall

    - import_tasks: tasks/main.yml
    - import_tasks: tasks/chrome-fedora25.yml
    - import_tasks: tasks/automationTools.yml
    - import_tasks: tasks/psycopg2.yml
    - import_tasks: tasks/repo.yml
    - import_tasks: tasks/dropbox.yml

